name: PUSH-UP 서버 배포

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  build-and-push:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 코드
        uses: actions/checkout@v4

      - name: 도커 QEMU 설정
        uses: docker/setup-qemu-action@v2

      - name: 도커 빌드 및 푸시
        uses: docker/setup-buildx-action@v3

      - name: 도커 허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: 도커 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
                ${{ secrets.DOCKER_USERNAME }}/push-up-server:latest
                ${{ secrets.DOCKER_USERNAME }}/push-up-server:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/push-up-server:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/push-up-server:buildcache,mode=max